apiVersion: database.platform.ohanyere.io/v1alpha1
kind: PostgreSQLClaim
metadata:
  name: metrics-api-postgres
  labels:
    app.kubernetes.io/name: metrics-api
    finops.ohanyere.io/cost-center: payments
spec:
  environment: dev
  databaseName: metrics-api
  size: small
  version: "16"
  backup:
    enabled: true
    retentionDays: 14
