apiVersion: cache.platform.ohanyere.io/v1alpha1
kind: RedisClaim
metadata:
  name: metrics-api-redis
  labels:
    app.kubernetes.io/name: metrics-api
    finops.ohanyere.io/cost-center: payments
spec:
  environment: dev
  size: small
  evictionPolicy: allkeys-lru
